Complete React Capstone
nevisende/ey-world pull request #1
Opened 2022-02-02 09:19 UTC by nevisende

# I completed all tasks:

## **API**
- [X] First you need to choose an API to base the development of the web app on. The API should allow you to get numeric values based on a parameter. We recommend that you choose an API that is open or needs an API key. If you choose an API that requires authentication, **you should implement it on your own**. 

## **Design**
- [X]  You should follow these [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), including:
  - [X] Colors (select one main color for your website).
  - [X] Typography: font face, size and weight.
  - [X]  Layout: composition and space between elements.

Original design idea by [Nelson Sakwa on Behance](https://www.behance.net/sakwadesignstudio).

- [X]  The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

## **Interactions**
- [X]  Home page
  - [X] When the page loads, the web app shows the list of categories that could be filtered out by some parameter, for example by the category name.
  - [X]  Along with the category name, you will display some numeric values per category that come from the API.
  - [X]  When the user clicks (or taps) on a category item, the application navigates to the details page.

- [X]  Details page
  - [X] In the details page, the web app retrieves data from the API to show detailed data in the category.
  - [X]  When the user clicks on the "Back" button (<), the user navigates to the home page.

## **Testing requirements**
- [X] Create unit tests for pure functions in your Redux code.
- [X]  Create integration tests for your application using the React Testing Library.
  - [X] You may need to mock the access to the API so that your tests don't send actual requests.
  - [X] You may need to mock the connection to the Redux Store.

## **Technical requirements**

- [X]  The project is a single-page application (SPA) built with React and Redux.
- [X]  The data retrieved from the API should be stored in the Redux store.
- [X]  You should filter the data that you retrieve from the API using a Filter stateless component.
- [X]  Every page (the main page and the pages for each item) should have a unique route within the SPA.
- [X] The project should be deployed and accessible online (add a link to the online version of your app to your README file).

2022-02-02 11:37 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @nevisende,

Good job so far!
✔️ Good documentation
✔️ Good video presentation
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
#### _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 11:37 UTC, TedLivist commented on README.md
> +# Ey-world
- [ ] You missed the GitFlow. Your pull request should be from Feature to Development but it is from Development to Main in your case. Please rebase your Pull Request before requesting for another review.

2022-02-02 11:37 UTC, TedLivist commented on README.md
> +## [Live Demo](https://ey-world.netlify.app/)
- [ ] On the live demo of your app, your **`detail`** route for a country does not the images as expected. Kindly fix that.

  ![kazakh-furkan](https://user-images.githubusercontent.com/36542986/152146184-34199f3e-0a92-4bd4-8487-072c8aba3e53.jpg)

2022-02-02 11:37 UTC, TedLivist commented on src/pages/Home.js
> +export default function Home() {
- [ ] I would recommend you follow the design template. On the design template, the homepage contains a descriptive landing section that describes the Homepage. Your app does not have the same. Afghanistan is a country and so does not describe your homepage as recommended in the design. Kindly fix your design.

  Your Implementation | Behance Design
  :---:|:---:
  ![furkan-afghan](https://user-images.githubusercontent.com/36542986/152145516-be91feaf-f139-419a-9d44-746e3e04d2c1.jpg) | ![furkan-origin-design](https://user-images.githubusercontent.com/36542986/152145521-9d5f4dbf-190d-4f7e-807f-58d0b591aff5.jpg)

- [ ] Locally, despite loading and saving the countries correctly (as evidenced in the redux logger on the console) your app does not display any countries. I think this has to do with setting headers for your axios (from the error message and maybe your API URL calls).

  ![furkan-header](https://user-images.githubusercontent.com/36542986/152142177-bece08c6-b64c-4eef-9efa-6eb9756f3484.jpg)

<hr/>

- [ ] From your app live link and presentation, I can see that your homepage is missing a filtering feature by which users can select filter your countries. Kindly add this feature.

  ![furkan-home](https://user-images.githubusercontent.com/36542986/152139571-c08085eb-c3e1-4969-bf60-487ae423d395.jpg)

2022-02-02 11:37 UTC, TedLivist commented on src/pages/Detail.js
> +export default function Detail() {
- [ ] Locally, I manually typed the Detail route, but your **`Detail`** page also does not display the country's images. Kindly fix this. Also, there seems to be a bug somewhere that adds the 'undefined' keyword to your API URL (see image).

  ![furkan-detail](https://user-images.githubusercontent.com/36542986/152143412-7bef4d6c-8f9a-46cc-968e-f02f146be7e0.jpg)

2022-02-02 11:37 UTC, TedLivist commented on src/pages/DetailState.js
> +export default function DetailState() {
- [ ] This same issue as in the Detail page highlighted above also occurs on this page. Kindly fix this.

2022-02-02 11:37 UTC, TedLivist commented on src/pages/DetailCity.js
> +export default function DetailCity() {
- [ ] The same issue as highlighted in the **Detail** page also occurs here. Kindly fix it.

2022-02-02 13:01 UTC, nevisende commented on README.md
> +# Ey-world
Hi, @TedLivist . Firstly this is about separated features and tasks. Not for capstones. Because I have to show you all changes in one PR for the capstone project.

2022-02-02 13:04 UTC, nevisende commented on README.md
> +## [Live Demo](https://ey-world.netlify.app/)
Because I have a limited API account so that you need to wait a little bit or you can try on different countries and also it is working on me. 
![Screenshot_2](https://user-images.githubusercontent.com/84407337/152159049-895155ef-2dc4-4a7d-aa5a-414729e6874c.png)

2022-02-02 13:04 UTC, TedLivist commented on README.md
> +# Ey-world
@nevisende, in the project requirements, it is specifically stated that you should use Gitflow (feature to dev), not Github Flow (dev to main).

2022-02-02 13:25 UTC, nevisende commented on src/pages/Home.js
> +export default function Home() {
Let me answer all:
- [X] Firstly Microverse describes in the document like this:
  **Design**
- You **should ** follow these [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), including:
  - Colors (select one main color for your website).
  - Typography: font face, size, and weight.
  - Layout: composition and space between elements.
  
And you can understand It is not a requirement and also it is  the same however I think you didn't realize second design:
![Screenshot_3](https://user-images.githubusercontent.com/84407337/152159923-fcb23e4a-6e6d-4132-bb10-7934a99bd9ec.png) (Yeah It does not perfectly match because they use specific images but I can't have them)

- [X] Second your problem: The error is from API and I explain in the video and submission detail. I think you didn't realize again :). To pass this error you need to apply[ these steps](https://stackoverflow.com/questions/37387711/page-loaded-over-https-but-requested-an-insecure-xmlhttprequest-endpoint/69359943#69359943) to your browser.
- [X) And Third: I think you get the wrong requirements because it is mentioned this:
  - You should filter the data that you retrieve from the API using a Filter stateless component.
And If you check [these lines](https://github.com/nevisende/ey-world/pull/1/files#r797601288) you can see I filtered data.

2022-02-02 13:33 UTC, nevisende commented on src/pages/Detail.js
> +export default function Detail() {
I don't need to do this because this is my software architect. I want to prevent direct access and I want them can access pages step by step. And before all, There is no requirement for this. Please pay attention to the documentation.

2022-02-02 13:35 UTC, nevisende commented on src/pages/DetailState.js
> +export default function DetailState() {
I have replied below

2022-02-02 13:35 UTC, nevisende commented on src/pages/DetailCity.js
> +export default function DetailCity() {
I have replied below

2022-02-02 13:37 UTC, TedLivist commented on src/pages/Home.js
> +export default function Home() {
@nevisende, you probably misunderstood my request. I didn't ask you to use same image or countries or color as the template. That's not what I highlighted.

I simply stated that your Homepage should should have some kind of header describing the page. As you can see in the design screenshot you shared, **EUROPE** is the continent that describes the other countries of page. In your own implementation, **AFGHANISTAN** does not describe the page. It is a country in itself and should be listed as part of the other countries. That's I recommended that you use a more descriptive caption for your Homepage. That's just what I highlighted. I had no issues with your images or color.

2022-02-02 13:39 UTC, nevisende commented
We have talked to each other and we have decided to request a second opinion.  I am looking forward to your response :)

2022-02-02 13:48 UTC, nevisende commented on src/pages/Home.js
> +export default function Home() {
@TedLivist  This depends on us, and you said **Your app does not have the same.** So I can show just countries I don't have to show same in the design. Also if you read the header it makes sense to you. (Header is COUNTRIES)

2022-02-02 13:51 UTC, TedLivist commented on src/pages/Home.js
> +export default function Home() {
> @TedLivist This depends on us, and you said **Your app does not have the same.** So I can show just countries I don't have to show same in the design. Also if you read the header it makes sense to you. (Header is COUNTRIES)

Yeah. I corrected the term.

2022-02-02 13:53 UTC, nevisende commented on README.md
> +# Ey-world
@TedLivist You are right in the normal tasks but this is a capstone project how can I show you all changes in a feature branch? Does it make sense?  And I did like this before capstone and it is approved.

2022-02-02 13:54 UTC, mke2111 commented
Project Under Second Opinion Review.
Kindly wait patiently for a response. 😄

2022-02-02 14:03 UTC, TedLivist commented on src/pages/Home.js
> +export default function Home() {
@nevisende as regards that second problem you highlighted, I followed your StackOverflow link during review for live demo and localhost. It works for the live demo as expected. And I think the errors are different. The link you sent me resolves the Insecure Content issue (see image). I enabled my local host to allow Insecure Content accordingly.

This is different from the error I highlighted.
![furkan-stack](https://user-images.githubusercontent.com/36542986/152168622-ac5158bc-29ab-42a2-b1a3-113e8c7160f0.jpg)

2022-02-02 14:07 UTC, nevisende commented on src/pages/Home.js
> +export default function Home() {
> @nevisende as regards that second problem you highlighted, I followed your StackOverflow link during review for live demo and localhost. It works for the live demo as expected. And I think the errors are different. The link you sent me resolves the Insecure Content issue (see image). I enabled my local host to allow Insecure Content accordingly.
> 
> This is different from the error I highlighted. ![furkan-stack](https://user-images.githubusercontent.com/36542986/152168622-ac5158bc-29ab-42a2-b1a3-113e8c7160f0.jpg)

Yes, it is different problem I sent it just for what should do, not to understand the problem.

2022-02-02 14:17 UTC, TedLivist commented on src/pages/Home.js
> +export default function Home() {
With regard to the last point, @nevisende, those are different requirements. Filtering data from the API is different from a user being able to search or filter contents on a page. As can see in the project requirements, those are different points.

  ![furkan-filter](https://user-images.githubusercontent.com/36542986/152170151-339074e5-d0a9-48cc-8608-cb2fc951391a.jpg)

2022-02-02 14:31 UTC, nevisende commented on src/pages/Home.js
> +export default function Home() {
I applied by country name so I have done the requirements

2022-02-02 14:36 UTC, TedLivist commented on src/pages/Home.js
> +export default function Home() {
There should be interactive feature on the homepage. 

> > @nevisende as regards that second problem you highlighted, I followed your StackOverflow link during review for live demo and localhost. It works for the live demo as expected. And I think the errors are different. The link you sent me resolves the Insecure Content issue (see image). I enabled my local host to allow Insecure Content accordingly.
> > This is different from the error I highlighted. ![furkan-stack](https://user-images.githubusercontent.com/36542986/152168622-ac5158bc-29ab-42a2-b1a3-113e8c7160f0.jpg)
> 
> Yes, it is different problem. I sent the link just for what should do, not to understand the problem.

The link you sent resolves a different issue.

2022-02-02 14:36 UTC, TedLivist commented on src/pages/Home.js
> +export default function Home() {
There should be interactive feature on the homepage. 

> > @nevisende as regards that second problem you highlighted, I followed your StackOverflow link during review for live demo and localhost. It works for the live demo as expected. And I think the errors are different. The link you sent me resolves the Insecure Content issue (see image). I enabled my local host to allow Insecure Content accordingly.
> > This is different from the error I highlighted. ![furkan-stack](https://user-images.githubusercontent.com/36542986/152168622-ac5158bc-29ab-42a2-b1a3-113e8c7160f0.jpg)
> 
> Yes, it is different problem. I sent the link just for what should do, not to understand the problem.

The link you sent resolves a different issue.

2022-02-02 14:36 UTC, TedLivist commented on src/pages/Home.js
> +export default function Home() {
> > @nevisende as regards that second problem you highlighted, I followed your StackOverflow link during review for live demo and localhost. It works for the live demo as expected. And I think the errors are different. The link you sent me resolves the Insecure Content issue (see image). I enabled my local host to allow Insecure Content accordingly.
> > This is different from the error I highlighted. ![furkan-stack](https://user-images.githubusercontent.com/36542986/152168622-ac5158bc-29ab-42a2-b1a3-113e8c7160f0.jpg)
> 
> Yes, it is different problem. I sent the link just for what should do, not to understand the problem.

The link you sent does not resolve the issue I highlighted. It resolves something entirely different.

2022-02-02 14:39 UTC, TedLivist commented on src/pages/Home.js
> +export default function Home() {
> I applied by country name so I have done the requirements

That's a different requirement. The homepage should have an interactive filtering feature for users, which it does not have.

2022-02-02 14:45 UTC, mke2111 reviewed
Hello @nevisende  👋,

_This is an additional review as a result of the second opinion request._

Great work done so far with the project. 👍🏽 I like the extra functionality of the dark theme you have added.

> I will endeavor to explain all changes requested so that we are all on the same footing.

In the [project requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md), it is not stated that you should compare the dev branch to the main branch. Only do this if it's stated in the guidelines such as in the group capstone you previously did. 
- Make this change as requested earlier on.

About this issue, I also had the same display. Images are not displayed yet.
> * [x]  On the live demo of your app, your **`detail`** route for a country does not the images as expected. Kindly fix that.
>       ![kazakh-furkan](https://user-images.githubusercontent.com/36542986/152146184-34199f3e-0a92-4bd4-8487-072c8aba3e53.jpg)
Since various APIs have some limitations based on the number of requests made and it is working just fine based on your screenshot, you may leave out this requested change.
- Consider this as an optional requirement.

Also, the homepage should have a filtering functionality. You have applied this feature but it should dynamic. A user should be able to choose to list only countries starting with the alphabet 'A' and only those that begin with the letter 'A' will be displayed. what you have implemented only sorts all countries in alphabetical order. Implement a filter to allow a user to filter in some way.
- Make this change as requested earlier on.

Manually configuring the detail route should not be a mandatory implementation.
- Consider this request optional.



Keep rocking 🚀 & Happy coding 💻

2022-02-02 16:07 UTC, nevisende commented on src/pages/Home.js
> +export default function Home() {
> > I applied by country name so I have done the requirements
> 
> That's a different requirement. The homepage should have an interactive filtering feature for users, which it does not have.

Man this is for the component job not user job please read carefully

2022-02-03 07:55 UTC, nevisende commented
I have done this by adding a filter to the home page and changing the branch from main to dev.

2022-02-03 09:37 UTC, DeliceLydia approved these changes
# Congratulations! 🎉🎉

## Hi @nevisende, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 09:37 UTC, DeliceLydia commented on README.md
> +
- [ ] Fix screenshot issue it doesn't show now

2022-02-03 09:57 UTC, merged

2022-02-03 09:59 UTC, nevisende commented on README.md
> +
Thanks, it appears now